use std::fmt;
use std::fmt::Display;

#[derive(Debug, Clone, PartialEq)]
pub enum Keyword {
    As,
    Async,
    Await,
    Break,
    Const,
    Continue,
    Crate,
    Dyn,
    Else,
    Enum,
    Extern,
    False,
    Fn,
    For,
    If,
    Impl,
    In,
    Let,
    Loop,
    Match,
    Mod,
    Move,
    Mut,
    Pub,
    Ref,
    Return,
    SelfType,
    Static,
    Struct,
    Super,
    Trait,
    True,
    Type,
    Unsafe,
    Use,
    Where,
    While,
}

impl Display for Keyword {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Keyword::As => "as",
            Keyword::Async => "async",
            Keyword::Await => "await",
            Keyword::Break => "break",
            Keyword::Const => "const",
            Keyword::Continue => "continue",
            Keyword::Crate => "crate",
            Keyword::Dyn => "dyn",
            Keyword::Else => "else",
            Keyword::Enum => "enum",
            Keyword::Extern => "extern",
            Keyword::False => "false",
            Keyword::Fn => "fn",
            Keyword::For => "for",
            Keyword::If => "if",
            Keyword::Impl => "impl",
            Keyword::In => "in",
            Keyword::Let => "let",
            Keyword::Loop => "loop",
            Keyword::Match => "match",
            Keyword::Mod => "mod",
            Keyword::Move => "move",
            Keyword::Mut => "mut",
            Keyword::Pub => "pub",
            Keyword::Ref => "ref",
            Keyword::Return => "return",
            Keyword::SelfType => "Self",
            Keyword::Static => "static",
            Keyword::Struct => "struct",
            Keyword::Super => "super",
            Keyword::Trait => "trait",
            Keyword::True => "true",
            Keyword::Type => "type",
            Keyword::Unsafe => "unsafe",
            Keyword::Use => "use",
            Keyword::Where => "where",
            Keyword::While => "while",
        };
        write!(f, "keyword:{}", s)
    }
}

impl Keyword {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "as" => Some(Keyword::As),
            "async" => Some(Keyword::Async),
            "await" => Some(Keyword::Await),
            "break" => Some(Keyword::Break),
            "const" => Some(Keyword::Const),
            "continue" => Some(Keyword::Continue),
            "crate" => Some(Keyword::Crate),
            "dyn" => Some(Keyword::Dyn),
            "else" => Some(Keyword::Else),
            "enum" => Some(Keyword::Enum),
            "extern" => Some(Keyword::Extern),
            "false" => Some(Keyword::False),
            "fn" => Some(Keyword::Fn),
            "for" => Some(Keyword::For),
            "if" => Some(Keyword::If),
            "impl" => Some(Keyword::Impl),
            "in" => Some(Keyword::In),
            "let" => Some(Keyword::Let),
            "loop" => Some(Keyword::Loop),
            "match" => Some(Keyword::Match),
            "mod" => Some(Keyword::Mod),
            "move" => Some(Keyword::Move),
            "mut" => Some(Keyword::Mut),
            "pub" => Some(Keyword::Pub),
            "ref" => Some(Keyword::Ref),
            "return" => Some(Keyword::Return),
            "Self" => Some(Keyword::SelfType),
            "static" => Some(Keyword::Static),
            "struct" => Some(Keyword::Struct),
            "super" => Some(Keyword::Super),
            "trait" => Some(Keyword::Trait),
            "true" => Some(Keyword::True),
            "type" => Some(Keyword::Type),
            "unsafe" => Some(Keyword::Unsafe),
            "use" => Some(Keyword::Use),
            "where" => Some(Keyword::Where),
            "while" => Some(Keyword::While),
            _ => None,
        }
    }
}